# -*- coding: utf-8 -*-
"""symptom2disease.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9xK-YADk4_jk3t2MvL_EmpFV1OUiJdo
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import pandas as pd
import pickle
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score
df_train = pd.read_csv('C:\\Users\\Prathima\\Desktop\\data science and ML\\firstd\\train.csv')
df_test = pd.read_csv('C:\\Users\\Prathima\\Desktop\\data science and ML\\firstd\\test.csv')
df_train.columns

training_data = df_train['text']
test_data = df_train['label']

#from df_test
pred_data = df_test['text'] #for prediction
pred_check = df_test['label'] #for accuracy score

model = make_pipeline(TfidfVectorizer(),MultinomialNB())

model.fit(training_data,test_data)

pred = model.predict(["I've had trouble falling asleep because of the rash's pain and itching. The skin on my fingers are starting to peel off. My nails have a few tiny cracks, which is really worrying. "])
print(pred)

#print(accuracy_score(pred_check,pred))

#pickle.dump(model,open('model.pkl','wb'))
